
server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev_database
    username: jdbc_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
